language: csharp
solution: src/Sclertta.Databases.sln
mono: none
dotnet: 2.1.202
script:
  - ./build/bump.sh $TRAVIS_TAG
  - ./build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./build/deploy.sh $NUGET_SOURCE $NUGET_API_KEY
  on:
    branch: master
  #   tags: true