language: csharp
solution: src/Sclertta.Databases.sln
mono: none
dotnet: 2.1.202
before_script:
branches:
  only:
  - master
  - develop
script:
  - ./build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./build/deploy.sh $NUGET_SOURCE $NUGET_APIKEY
  on:
    branch: master